#include "MurIncassable.h"




bool MurIncassable::MCreation()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-10--3302b6d6:126ebb3b755:-8000:0000000000001201 begin
{
    return false;
}
// section -64--88-0-10--3302b6d6:126ebb3b755:-8000:0000000000001201 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool MurIncassable::MDestruction()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-10--1cfdf253:126f6ed6de7:-8000:000000000000109B begin
{
    return false;
}
// section -64--88-0-10--1cfdf253:126f6ed6de7:-8000:000000000000109B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
