#include "ObjetPrenable.h"




bool ObjetPrenable::MObjetPris()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-10--3302b6d6:126ebb3b755:-8000:0000000000001192 begin
{
    return false;
}
// section -64--88-0-10--3302b6d6:126ebb3b755:-8000:0000000000001192 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
