#include "ObjetMalus.h"




bool ObjetMalus::MDestruction()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-10--3302b6d6:126ebb3b755:-8000:0000000000001217 begin
{
    return false;
}
// section -64--88-0-10--3302b6d6:126ebb3b755:-8000:0000000000001217 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool ObjetMalus::MAppliquerEffet(Joueur _joueur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-10--5300fea0:126f605becf:-8000:0000000000001047 begin
{
    return false;
}
// section -64--88-0-10--5300fea0:126f605becf:-8000:0000000000001047 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
