#include "Plateau.h"




bool Plateau::MCreation(MurCassableAvecObjetPrenable _listeMurCassableAvecObjetPrenable)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-10--26a2fe8b:126f83ac6e5:-8000:00000000000010B1 begin
{
    return false;
}
// section -64--88-0-10--26a2fe8b:126f83ac6e5:-8000:00000000000010B1 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Plateau::MDestruction()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-10--26a2fe8b:126f83ac6e5:-8000:00000000000010B3 begin
{
    return false;
}
// section -64--88-0-10--26a2fe8b:126f83ac6e5:-8000:00000000000010B3 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Plateau::MSetBombe()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-10--1cfdf253:126f6ed6de7:-8000:00000000000010A4 begin
{
    return false;
}
// section -64--88-0-10--1cfdf253:126f6ed6de7:-8000:00000000000010A4 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Plateau::MPlacerMursIncassables()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-10--26a2fe8b:126f83ac6e5:-8000:00000000000010B5 begin
{
    return false;
}
// section -64--88-0-10--26a2fe8b:126f83ac6e5:-8000:00000000000010B5 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Plateau::MPlacerMursCassables(MurCassableAvecObjetPrenable _listMurCassableAvecObjetPrenable)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-10--26a2fe8b:126f83ac6e5:-8000:00000000000010B7 begin
{
    return false;
}
// section -64--88-0-10--26a2fe8b:126f83ac6e5:-8000:00000000000010B7 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Case Plateau::MGetCase(sf::Vector2i _coordonnees)
{
	return Case(); //jte laisse calculer ça oli, on a un tableau à une dimension(tout aligné), faut retourner la case selon le Vector2i 
}

Case Plateau::MGetPlateau()

{
	return *m_Case;
}
