#include "BomberDose.h"

 {


bool BomberDose::MCreatePlayer(Joueur _joueurs, Plateau _plateau)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-10--26a2fe8b:126f83ac6e5:-8000:00000000000010EE begin
{
    return false;
}
// section -64--88-0-10--26a2fe8b:126f83ac6e5:-8000:00000000000010EE end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool BomberDose::MGetJoueur(int _indice)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-10--26a2fe8b:126f83ac6e5:-8000:00000000000010F2 begin
{
    return false;
}
// section -64--88-0-10--26a2fe8b:126f83ac6e5:-8000:00000000000010F2 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
