#include "Case.h"

 {


bool Case::MCreation()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-10--26a2fe8b:126f83ac6e5:-8000:00000000000010DA begin
{
    return false;
}
// section -64--88-0-10--26a2fe8b:126f83ac6e5:-8000:00000000000010DA end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Case::MIsEmpty()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-10--1cfdf253:126f6ed6de7:-8000:00000000000010B2 begin
{
    return false;
}
// section -64--88-0-10--1cfdf253:126f6ed6de7:-8000:00000000000010B2 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Case::MFill()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-10--1cfdf253:126f6ed6de7:-8000:00000000000010B4 begin
{
    return false;
}
// section -64--88-0-10--1cfdf253:126f6ed6de7:-8000:00000000000010B4 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
