#include "Timer.h"

 {


bool Timer::MStartTimer()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-10--3302b6d6:126ebb3b755:-8000:00000000000011AF begin
{
    return false;
}
// section -64--88-0-10--3302b6d6:126ebb3b755:-8000:00000000000011AF end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

float Timer::MGetTime()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-10--3302b6d6:126ebb3b755:-8000:00000000000011B1 begin
{
    return 0.0;
}
// section -64--88-0-10--3302b6d6:126ebb3b755:-8000:00000000000011B1 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Timer::MRestartTimer()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-10--3302b6d6:126ebb3b755:-8000:00000000000011B6 begin
{
    return false;
}
// section -64--88-0-10--3302b6d6:126ebb3b755:-8000:00000000000011B6 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
