#include "BonusBombe.h"



bool BonusBombe::MAppliquerEffet(Joueur _joueur)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-10--5300fea0:126f605becf:-8000:0000000000001056 begin
{
    return false;
}
// section -64--88-0-10--5300fea0:126f605becf:-8000:0000000000001056 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
