#include "Joueur.h"

 {


bool Joueur::MPoserBombe(int _puissance)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-10--26a2fe8b:126f83ac6e5:-8000:00000000000010AF begin
{
    return false;
}
// section -64--88-0-10--26a2fe8b:126f83ac6e5:-8000:00000000000010AF end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Joueur::MUpdate()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-10--1cfdf253:126f6ed6de7:-8000:000000000000109F begin
{
    return false;
}
// section -64--88-0-10--1cfdf253:126f6ed6de7:-8000:000000000000109F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Joueur::MJouer()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-10--26a2fe8b:126f83ac6e5:-8000:00000000000010C0 begin
{
    return false;
}
// section -64--88-0-10--26a2fe8b:126f83ac6e5:-8000:00000000000010C0 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Plateau Joueur::MGetPlateau()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-10--26a2fe8b:126f83ac6e5:-8000:00000000000010D3 begin
{
}
// section -64--88-0-10--26a2fe8b:126f83ac6e5:-8000:00000000000010D3 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Joueur::MGetPosition()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-10--26a2fe8b:126f83ac6e5:-8000:00000000000010D5 begin
{
    return false;
}
// section -64--88-0-10--26a2fe8b:126f83ac6e5:-8000:00000000000010D5 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Joueur::MSetPosition(void _coordonnees)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-10--26a2fe8b:126f83ac6e5:-8000:00000000000010D7 begin
{
    return false;
}
// section -64--88-0-10--26a2fe8b:126f83ac6e5:-8000:00000000000010D7 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
