#include "MurCassableAvecObjetPrenable.h"

 {


bool MurCassableAvecObjetPrenable::MCreation()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-10--3302b6d6:126ebb3b755:-8000:000000000000120B begin
{
    return false;
}
// section -64--88-0-10--3302b6d6:126ebb3b755:-8000:000000000000120B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool MurCassableAvecObjetPrenable::MDestruction()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-10--3302b6d6:126ebb3b755:-8000:000000000000120D begin
{
    return false;
}
// section -64--88-0-10--3302b6d6:126ebb3b755:-8000:000000000000120D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
