#include "ObjetCassableEtPrennable.h"

 {


bool ObjetCassableEtPrennable::MCreation()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-10--3302b6d6:126ebb3b755:-8000:00000000000011FD begin
{
    return false;
}
// section -64--88-0-10--3302b6d6:126ebb3b755:-8000:00000000000011FD end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool ObjetCassableEtPrennable::MObjetPris()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-10--3302b6d6:126ebb3b755:-8000:00000000000011FF begin
{
    return false;
}
// section -64--88-0-10--3302b6d6:126ebb3b755:-8000:00000000000011FF end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
